"""Add meta and reconfigure file for integration with dammit

Revision ID: 21998f87540f
Revises: 4d4d50316342
Create Date: 2019-11-15 21:09:06.599940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21998f87540f'
down_revision = '4d4d50316342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('converted', sa.Boolean(), nullable=True))
    op.drop_constraint('files_pkey', 'files')
    op.alter_column(table_name='files', column_name='id', new_column_name='file_id')
    op.create_primary_key(table_name='files', constraint_name='files_pkey', columns=['file_id'])
    #sa.PrimaryKeyConstraint('file_id', 'files')
    op.drop_index('author', table_name='files')
    op.drop_index('file_hash', table_name='files')
    op.drop_column('files', 'author')
    op.drop_column('files', 'name')

    op.add_column('harolds', sa.Column('file_id', sa.Integer(), nullable=True))
    op.drop_constraint('harolds_pkey', 'harolds')
    op.alter_column(table_name='harolds', column_name='id', new_column_name='harold_id')
    op.create_primary_key(table_name='harolds', constraint_name='harolds_pkey', columns=['harold_id'])
    #sa.PrimaryKeyConstraint('harold_id', 'harolds')
    op.drop_index('file_hash_index', table_name='harolds')
    op.drop_index('owner', table_name='harolds')
    op.create_foreign_key(None, 'harolds', 'files', ['file_id'], ['file_id'])
    op.drop_column('harolds', 'file_hash')

    op.create_table('meta',
        sa.Column('meta_id', sa.Integer(), nullable=False),
        sa.Column('file_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('author', sa.Text(), nullable=False),
        sa.Column('beat_times', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
        sa.PrimaryKeyConstraint('meta_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harolds', sa.Column('file_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('harolds', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'harolds', type_='foreignkey')
    op.create_index('owner', 'harolds', ['owner'], unique=False)
    op.create_index('file_hash_index', 'harolds', ['file_hash'], unique=False)
    op.drop_column('harolds', 'harold_id')
    op.drop_column('harolds', 'file_id')
    op.add_column('files', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('files', sa.Column('author', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index('file_hash', 'files', ['file_hash'], unique=False)
    op.create_index('author', 'files', ['author'], unique=False)
    op.drop_column('files', 'file_id')
    op.drop_column('files', 'converted')
    op.drop_table('meta')
    # ### end Alembic commands ###
